---

- hosts: all
  vars:
    girder_update: no
    girder_force: no
    girder_web: yes
    girder_user: wongwongwong
    girder_path: "/home/{{ girder_user }}/girder"
    girder_always_build_assets: yes
    girder_host: localhost
    girder_port: 8080
    girder_password: "parionistersenestionlityper"
    girder_virtualenv: venv

  pre_tasks:

    - name: Create Girder User
      girder:
        port: "{{ girder_port }}"
        user:
          firstName: "Wong"
          lastName: "Wong"
          login: "{{ girder_user }}"
          password: "{{ girder_password }}"
          email: "wong@wong.wong"
          admin: yes
        state: present

    - name: Create filesystem assetstore
      girder:
        username: "{{ girder_user }}"
        password: "{{ girder_password }}"
        port: "{{ girder_port }}"
        assetstore:
          name: "Filesystem Assetstore"
          type: "filesystem"
          root: "/data/"
          current: true
        state: present

    - name: Restart the server
      girder:
        username: "{{ girder_user }}"
        password: "{{ girder_password }}"
        port: "{{ girder_port }}"
        put:
          path: "system/restart"

    - name: Wait until server restarts
      wait_for:
        port: "{{ girder_port }}"
        delay: 5
