---

- hosts: all
  vars:
    girder_update: no
    girder_force: no
    girder_web: yes
    girder_user: wongwongwong
    girder_path: "/home/{{ girder_user }}/girder"
    girder_always_build_assets: yes
    girder_host: localhost
    girder_port: 8080
    girder_password: "parionistersenestionlityper"

  pre_tasks:

    - name: Create Girder user
      user:
        password: "parionistersenestionlityper"
        name: "{{ girder_user }}"
      become: yes
      become_method: sudo
      become_user: circleci

  roles:
    - role: girder.girder
      become: yes
      become_user: "{{ girder_user }}"
