---

- hosts: all
  vars:
    girder_update: no
    girder_force: no
    girder_web: yes
    girder_user: wongwongwong
    girder_path: "/home/{{ girder_user }}/girder"
    girder_always_build_assets: yes
    girder_host: localhost
    girder_port: 8080
    girder_password: "parionistersenestionlityper"

  pre_tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      become: yes
      become_user: root
      when: ansible_os_family == "Debian"

    - name: Create Girder user
      user:
        firstName: "Wong"
        lastName: "Wong"
        login: "wongwongwong"
        password: "parionistersenestionlityper"
        email: "wong@wong.wong"
        admin: yes
        name: "{{ girder_user }}"
      become: yes
      become_user: root

  roles:
    - role: girder.girder
      become: yes
      become_user: "{{ girder_user }}"
