---
- hosts: localhost
  vars:
    girder_host: girder
    girder_port: 8080
    girder_user: "wongwongwong"
    girder_password: "parionistersenestionlityper"

  tasks:
    - name: Creating User
      girder:
        port: "{{ girder_port }}"
        user:
          firstName: "Wong"
          lastName: "Wong"
          login: "wongwongwong"
          password: "parionistersenestionlityper"
          email: "wong@wong.wong"
          admin: yes
        state: present

    - name: Creating Filesystem Assetstore
      girder:
        username: "{{ girder_user }}"
        password: "{{ girder_password }}"
        port: "{{ girder_port }}"
        assetstore:
          name: "Filesystem Assetstore"
          type: "filesystem"
          root: "/data/"
          current: true
        state: present

    - name: Restarting the Server
      girder:
        username: "{{ girder_user }}"
        password: "{{ girder_password }}"
        port: "{{ girder_port }}"
        put:
          path: "system/restart"

    - name: Waiting Until Server Restarts
      wait_for:
        port: "{{ girder_port }}"
        delay: 5
